### ISSUE TITLE
Docker setup

### ISSUE THREAD

**Issue by kevinlinxc** [jstrieb/paperify#1]
It would be nice to not have to figure out all the dependencied, esp on windows. Would it be possible to create a docker setup for paperify?

**Comment by jstrieb** [comment]
I created a [`jstrieb/paperify`](https://hub.docker.com/repository/docker/jstrieb/paperify/general) Docker image. The following command will now work.

```
docker run \
  --rm \
  -it \
  --volume "$(pwd)/build":/root/build \
  jstrieb/paperify \
    --from-format html \
    "https://research.swtch.com/bell-labs" \
    build/cox.pdf
```

In general, any `paperify [...]` command can be replaced with `docker run jstrieb/paperify [...]`, plus a few additional Docker options to make sure the generated paper can be extracted from the container.
